/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class CmdAgentImpl */

#ifndef _Included_CmdAgentImpl
#define _Included_CmdAgentImpl
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     CmdAgentImpl
 * Method:    getCurrentLocalTime
 * Signature: (LGetLocalTime;)LGetLocalTime;
 */
JNIEXPORT jobject JNICALL Java_CmdAgentImpl_getCurrentLocalTime
  (JNIEnv *, jobject, jobject);

/*
 * Class:     CmdAgentImpl
 * Method:    getlocalVersion
 * Signature: (LGetVersion;)LGetVersion;
 */
JNIEXPORT jobject JNICALL Java_CmdAgentImpl_getlocalVersion
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
